site_name: Jonas Ferreira
theme:
  name: material
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: turn off the light
    - scheme: slate 
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: turn on the light
