site_name: Jonas Ferreira

nav:
    - jonas: index.md
    - scripts : scripts.md
#    - Blog: blog.md
#    - Novel: novel.md
    - cv: cv.md

theme:
  name: material
  favicon: assets/images/terminal.svg
  icon:
    logo: octicons/terminal-16
  palette: 
    - scheme: default
      primary: indigo
      icon:
      logo: material/library
      toggle:
        icon: material/toggle-switch-off-outline 
        name: turn off the light
    - scheme: slate 
      primary: red
      toggle:
        icon: material/toggle-switch
        name: turn on the light
  features: 
    - toc.follow
  font:
    code: Fira Code

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/jonasmcferreira
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jonasferreira/
#    - icon: fontawesome/brands/medium
#      link: https://medium.com/@thejonas

copyright: code is love

extra_css:
  - stylesheets/extra.css

plugins: []

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

