site_name: Jonas Ferreira

nav:
    - Home: index.md
    - Blog: blog.md
    - CV: cv.md
    

theme:
  name: material
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: turn off the light
    - scheme: slate 
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: turn on the light
  features: 
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/jonasmcferreira
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jonasferreira/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@thejonas
  generator: false

copyright: the code is the truth <3