site_name: Jonas Ferreira

nav:
    - Home: index.md
    - Blog: blog.md

theme:
  name: material
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: turn off the light
    - scheme: slate 
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: turn on the light
  features:
    - header.autohide


